spring:
  jpa:
    show-sql: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/vueblog?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456